### PR TITLE
Do not allow trailing commas in calls without parenthesis

### LINKED ISSUE #1548: Ruby rejects `foo 1,` but YARP accepts it
```
$ ./local/bin/irb -ryarp
irb(main):001> RubyVM::AbstractSyntaxTree.parse("foo 1,")
<internal:ast>:59:in `parse': syntax error, unexpected end-of-input (SyntaxError)
foo 1,
      ^

        from (irb):1:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /home/mame/work/ruby/local/lib/ruby/gems/3.3.0+0/gems/irb-1.8.1/exe/irb:9:in `<top (required)>'
        from ./local/bin/irb:25:in `load'
        from ./local/bin/irb:25:in `<main>'
irb(main):002> YARP.parse("foo 1,")
=>
#<YARP::ParseResult:0x00007fe4d95a22b8
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007fe4d93f9218 @offsets=[0], @source="foo 1,">,
 @value=
  @ ProgramNode (location: (0...5))
├── locals: []
└── statements:
    @ StatementsNode (location: (0...5))
    └── body: (length: 1)
        └── @ CallNode (location: (0...5))
            ├── receiver: ∅
            ├── call_operator_loc: ∅
            ├── message_loc: (0...3) = "foo"
            ├── opening_loc: ∅
            ├── arguments:
            │   @ ArgumentsNode (location: (4...5))
            │   └── arguments: (length: 1)
            │       └── @ IntegerNode (location: (4...5))
            │           └── flags: decimal
            ├── closing_loc: ∅
            ├── block: ∅
            ├── flags: ∅
            └── name: "foo",
 @warnings=[]>
```

### PR DESCRIPTION
**Pull request by haldun**
Closes #1548

### CODE REVIEW

File: src/yarp.c [hunk 1]
```diff
@@ -9771,7 +9776,7 @@ parse_arguments_list(yp_parser_t *parser, yp_arguments_t *arguments, bool accept
         // If we get here, then the subsequent token cannot be used as an infix
         // operator. In this case we assume the subsequent token is part of an
         // argument to this method call.
-        parse_arguments(parser, arguments, true, YP_TOKEN_EOF);
+        parse_arguments(parser, arguments, true, YP_TOKEN_EOF, false);
```
Comment (kddnewton) [inline src/yarp.c:9779]: Instead of passing this argument here, could we instead put the check for the trailing comma here? That way it wouldn't be inside `parse_arguments` at all and we could just put it where you're currently passing `false`

**Review by kddnewton — CHANGES_REQUESTED** [review]

File: src/yarp.c [hunk 2]
```diff
@@ -9773,6 +9773,12 @@ parse_arguments_list(yp_parser_t *parser, yp_arguments_t *arguments, bool accept
         // argument to this method call.
         parse_arguments(parser, arguments, true, YP_TOKEN_EOF);
 
+        // If we have done with the arguments and still not consumed the comma, then we have a trailing comma
+        // where we need to check whether it is allowed or not.
+        if (parser->previous.type == YP_TOKEN_COMMA && !match1(parser, YP_TOKEN_SEMICOLON)) {
```
Comment (kddnewton) [inline src/yarp.c:9778]: I think the check for semicolon here would allow `foo 1,;`. Is that intentional?

File: src/yarp.c [hunk 3]
```diff
@@ -9773,6 +9773,12 @@ parse_arguments_list(yp_parser_t *parser, yp_arguments_t *arguments, bool accept
...
+            yp_diagnostic_list_append(&parser->error_list, parser->previous.start, parser->previous.end, YP_ERR_EXPECT_ARGUMENT);
+        }
```
Comment (kddnewton) [inline src/yarp.c:9780]:
```suggestion
        // If we have done with the arguments and still not consumed the comma,
        // then we have a trailing comma where we need to check whether it is
        // allowed or not.
        if (parser->previous.type == PM_TOKEN_COMMA && !match1(parser, PM_TOKEN_SEMICOLON)) {
            pm_parser_err_previous(parser, PM_ERR_EXPECT_ARGUMENT);
        }
```

Comment (kddnewton) [reply src/yarp.c:9780]: Sorry this took so long, but yeah this looks good. I've added a suggestion here for how to update it since it has been so long.

**Review by kddnewton — CHANGES_REQUESTED** [review]

**Review by kddnewton — APPROVED** [review]
