### PR TITLE
Fix lexer skipping tokens when heredoc body is unterminated

### LINKED ISSUE #3911: Prism.lex_compat creates wrong on_sp token when used with heredoc and unclosed embexpr
```ruby
Prism.lex_compat("<<A+B\n\#{C").value
# => [[[1, 0], :on_heredoc_beg, "<<A", BEG], [[1, 3], :on_sp, "+B\n\#{C", BEG]]
```

Found in IRB's truffleruby ci failure. Actual ruby code:
https://github.com/ruby/irb/blob/342f57b2d0a39c519a53e6d5a3938f6235119c9c/test/irb/test_ruby_lex.rb#L17-L21
```ruby
①+<<A-②
#{③*<<B/④
#{⑤&<<C|⑥
```
This failing test is not important in IRB anymore and I think it will be removed soon (in https://github.com/ruby/irb/pull/1160).

### PR DESCRIPTION
**Pull request by Earlopain**
Fixes #3911

When we hit EOF and still have lex modes left, it means some content was unterminated.
Heredocs specifically have logic that needs to happen when the body finished lexing.
If we don't reset the mode back to how it was before, it will not continue lexing at the correct place.

Also skips the heredoc_end tokens that prism emits in the ripper translator. They are for bookkeeping only and ripper doesn't do so.

### CODE REVIEW

File: test/prism/lex_test.rb [hunk 1]
```diff
@@ -48,11 +48,94 @@ def test_parse_lex_file
...
+    def test_lex_interpolation_unterminated_with_content
+      # No trailing newline.
+      # FIXME: Emits EOL twice.
+      assert_lexed(<<~'RUBY'.strip, <<~'LEXED')
+        "#{C
+      RUBY
+        STRING_BEGIN(1,0)-(1,1)("\"")
+        EMBEXPR_BEGIN(1,1)-(1,3)("\#{")
+        CONSTANT(1,3)-(1,4)("C")
+        EOF(1,4)-(1,4)("")
```
Comment (Earlopain) [inline test/prism/lex_test.rb]: This containing EOF twice is preexisting and not caused by this change

File: test/prism/lex_test.rb [hunk 2]
```diff
@@ -48,11 +48,94 @@ def test_parse_lex_file
     end
 
     if RUBY_VERSION >= "3.3"
-      def test_lex_compare
-        prism = Prism.lex_compat(File.read(__FILE__), version: "current").value
-        ripper = Ripper.lex(File.read(__FILE__))
+      def test_lex_compat
+        source = "foo bar"
```
Comment (Earlopain) [inline test/prism/lex_test.rb:52]: I added heredocs below where ripper doesn't do the state correctly. So I just have it parse some other source

File: src/prism.c [hunk 3]
```diff
@@ -9856,6 +9862,14 @@ parser_lex(pm_parser_t *parser) {
             // We'll check if we're at the end of the file. If we are, then we
             // need to return the EOF token.
             if (parser->current.end >= parser->end) {
+                // We may be missing closing tokens. We should pop modes one by one
+                // to do the appropriate cleanup like moving next_start for heredocs.
+                // Only when no mode is remaining will we actually emit the EOF token.
+                if (parser->lex_modes.current->mode != PM_LEX_DEFAULT) {
+                    lex_mode_pop(parser);
+                    goto switch_lex_mode;
```
Comment (Earlopain) [inline src/prism.c]: Unsure about this but it was the easiest way to accomplish it. There are already gotos in the method (`lex_next_token`) so maybe it is fine?

File: test/prism/lex_test.rb [hunk 4]
```diff
@@ -48,11 +48,94 @@ def test_parse_lex_file
...
+        HEREDOC_END(3,0)-(3,0)("")
+        PLUS(1,3)-(1,4)("+")
+        CONSTANT(1,4)-(1,5)("B")
+        NEWLINE(1,5)-(2,0)("\n")
+        EOF(2,3)-(3,0)("\n")
+      LEXED
+    end
+
+    def assert_lexed(code, expected)
+      actual = Prism.lex(code).value.map { |token| token[0].pretty_inspect }
```
Comment (Earlopain) [inline test/prism/lex_test.rb]: I don't think there will be many tests of this sort, for now writing them like this seems fine. I added some errors tests but not everything will be visible there (like double EOF). The error test highlights `+` after the heredoc identifer which it didn't do before so if you think that is enough I can remove this

File: src/prism.c (hunk 3 above)
Comment (kddnewton) [reply src/prism.c]: Could this just be return parser_lex?

File: test/prism/lex_test.rb [hunk 5]
```diff
@@ -48,11 +48,94 @@ def test_parse_lex_file
...
+        ripper = Ripper.lex(source)
         assert_equal(ripper, prism)
       end
     end
+
+    def test_lex_interpolation_unterminated
+      assert_lexed(<<~'RUBY'.strip, <<~'LEXED')
+        "#{
+      RUBY
+        STRING_BEGIN(1,0)-(1,1)("\"")
```
Comment (kddnewton) [inline test/prism/lex_test.rb]: I really don't like these kinds of snapshot tests because they're usually very difficult to update, and it's not clear what exactly is being tested. Could you instead lex the content, get the tokens, and make assertions against the specific behavior you're looking for?

File: src/prism.c (hunk 3 above)
Comment (Earlopain) [reply src/prism.c]: Ah, yeah

File: test/prism/lex_test.rb (hunk 5 above)
Comment (Earlopain) [reply test/prism/lex_test.rb]: I simplified it a bit. Token type was really the only thing I was looking for. Is this good or still too much?
