### PR TITLE
Fix a token incompatibility for `Prism::Translation::Parser`

### LINKED ISSUE #2512: `Prism::Translation::Parser` incompatibility tokens for heredoc with multiple empty lines
> [!NOTE]
> This is similar to #2510, but it has been opened as a separate issue due to a different context.

Incompatibility content of `:tSTRING_END` token for heredoc with multiple empty lines between Parser gem and Prism:

```console
$ cat example.rb
<<~TEXT
hi


TEXT
```

## Expected Behavior

The return values of `Parser::Ruby33#tokenize` and `Prism::Translation::Parser33#tokenize` match.

## Actual Behavior

The return values of `Parser::Ruby33#tokenize` and `Prism::Translation::Parser33#tokenize` don't match:

```ruby
require 'parser/ruby33'

buffer = Parser::Source::Buffer.new('example.rb')
buffer.source = File.read('example.rb')

p Parser::Ruby33.new.tokenize(buffer).last

#=> [[:tSTRING_BEG, ["<<\"", #<Parser::Source::Range example.rb 0...7>]], [:tSTRING_CONTENT, ["hi\n", #<Parser::Source::Range example.rb 8...11>]], [:tSTRING_CONTENT, ["\n", #<Parser::Source::Range example.rb 11...12>]], [:tSTRING_CONTENT, ["\n", #<Parser::Source::Range example.rb 12...13>]], [:tSTRING_END, ["TEXT", #<Parser::Source::Range example.rb 13...17>]], [:tNL, [nil, #<Parser::Source::Range example.rb 7...8>]]]

require 'prism'
require 'prism/translation/parser33'

p Prism::Translation::Parser33.new.tokenize(buffer).last
#=> [[:tSTRING_BEG, ["<<\"", #<Parser::Source::Range example.rb 0...7>]], [:tSTRING_CONTENT, ["hi\n", #<Parser::Source::Range example.rb 8...11>]], [:tSTRING_CONTENT, ["\n", #<Parser::Source::Range example.rb 11...12>]], [:tSTRING_CONTENT, ["\n", #<Parser::Source::Range example.rb 12...13>]], [:tSTRING_END, ["TEXT\n", #<Parser::Source::Range example.rb 13...18>]], [:tNL, [nil, #<Parser::Source::Range example.rb 7...8>]]]
```

`Prism::Translation::Parser33#tokenize` returns unexpected content of `:tSTRING_END` token.

## Background

Found due to incompatibility with RuboCop's `Layout/EmptyLines` cop.

### PR DESCRIPTION
**Pull request by koic**
Fixes #2512.

This PR fixes a token incompatibility between Parser gem and `Prism::Translation::Parser` for `HEREDOC_END` with a newline.

### CODE REVIEW

**Review by kddnewton — APPROVED** [review]

**Comment by kddnewton** [comment]
Do we need to handle \r\n as well?

**Comment by koic** [comment]
Sure! I've updated this PR.

**Review by kddnewton — APPROVED** [review]

File: lib/prism/translation/parser/lexer.rb [hunk 1]
```diff
@@ -304,7 +304,10 @@ def to_a
             when :tSTRING_DVAR
               value = nil
             when :tSTRING_END
-              if token.type == :REGEXP_END
+              if token.type == :HEREDOC_END && value.end_with?("\n")
+                value = value.sub(/\r?\n\z/, '')
+                location = Range.new(source_buffer, offset_cache[token.location.start_offset], offset_cache[token.location.end_offset - 1])
```
Comment (kddnewton) [inline lib/prism/translation/parser/lexer.rb:309]: I think the `end_offset - 1` will need to be `-2` for `\r\n`

**Review by kddnewton — APPROVED** [review]
