### PR TITLE
Fix parsing singular bare hash argument

### LINKED ISSUE #494: Singular bare hash arguments
```ruby
outbuf = IO.popen(cmd, :err => [:child, :out], &:read)
```

### PR DESCRIPTION
**Pull request by haldun**
Fixes #494

### CODE REVIEW

File: src/yarp.c [hunk 1]
```diff
@@ -4923,7 +4923,9 @@ parse_arguments(yp_parser_t *parser, yp_node_t *arguments, yp_token_type_t termi
           argument = bare_hash;
 
           // Then parse more if we have a comma
-          if (accept(parser, YP_TOKEN_COMMA)) parse_assocs(parser, argument);
+          if (accept(parser, YP_TOKEN_COMMA) && !match_type_p(parser, YP_TOKEN_AMPERSAND)) {
```
Comment (kddnewton) [inline src/yarp.c:4926]: Instead of checking for just ampersand, can you check `token_begins_expression_p`? It should catch more.

**Review by kddnewton — CHANGES_REQUESTED** [review]
