### PR TITLE
Fix parsing shadow args in lambda blocks

### LINKED ISSUE #1583: Ruby rejects `->a;b{}` but YARP accepts it
```
$ ruby -ce "->a;b{}"
-e:1: syntax error, unexpected ';', expecting `do' for lambda or tLAMBEG
->a;b{}
-e:1: syntax error, unexpected tLAMBEG, expecting end-of-input
->a;b{}
-e: compile error (SyntaxError)
```

```ruby
irb(main):001> YARP.parse '->a;b{}'
=> 
#<YARP::ParseResult:0x00000001049ce4d8
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x0000000104122410 @offsets=[0], @source="->a;b{}">,
 @value=
  @ ProgramNode (location: (1,0)-(1,7))
  ├── locals: []
  └── statements:
      @ StatementsNode (location: (1,0)-(1,7))
      └── body: (length: 1)
          └── @ LambdaNode (location: (1,0)-(1,7))
              ├── locals: [:a, :b]
              ├── operator_loc: (1,0)-(1,2) = "->"
              ├── opening_loc: (1,5)-(1,6) = "{"
              ├── closing_loc: (1,6)-(1,7) = "}"
              ├── parameters:
              │   @ BlockParametersNode (location: (1,2)-(1,5))
              │   ├── parameters:
              │   │   @ ParametersNode (location: (1,2)-(1,3))
              │   │   ├── requireds: (length: 1)
              │   │   │   └── @ RequiredParameterNode (location: (1,2)-(1,3))
              │   │   │       └── name: :a
              │   │   ├── optionals: (length: 0)
              │   │   ├── rest: ∅
              │   │   ├── posts: (length: 0)
              │   │   ├── keywords: (length: 0)
              │   │   ├── keyword_rest: ∅
              │   │   └── block: ∅
              │   ├── locals: (length: 1)
              │   │   └── @ BlockLocalVariableNode (location: (1,4)-(1,5))
              │   │       └── name: :b
              │   ├── opening_loc: ∅
              │   └── closing_loc: ∅
              └── body: ∅,
 @warnings=[]>
```

### PR DESCRIPTION
**Pull request by haldun**
Closes #1583

### CODE REVIEW

File: src/prism.c [hunk 1]
```diff
@@ -9782,7 +9782,7 @@ parse_block_parameters(
     }
 
     pm_block_parameters_node_t *block_parameters = pm_block_parameters_node_create(parser, parameters, opening);
-    if (accept1(parser, PM_TOKEN_SEMICOLON)) {
+    if (accept1(parser, PM_TOKEN_SEMICOLON) && opening->type != PM_TOKEN_NOT_PROVIDED) {
```
Comment (kddnewton) [inline src/prism.c:9785]: I think these conditions need to be reserved since accept1 will advance the lexer

**Review by kddnewton — CHANGES_REQUESTED** [review]

File: src/prism.c (hunk 1 above)
Comment (haldun) [reply src/prism.c:9785]: Sorry you mean "reversed"?

Comment (kddnewton) [reply src/prism.c:9785]: Ahh sorry yes reversed

**Review by kddnewton — APPROVED** [review]
