### PR TITLE
Don't add an invalid identifier capture to locals

### LINKED ISSUE #1815: MatchWriteNode `/(?<a b>)/ =~ s` has wrong locals
For `/regexp_with_named_capture/ =~ s`, group name which is not valid as a local variable name has no effect.
```ruby
/(?<a>.)(?<@a>.)(?<$a>.)(?<a b>.)/ =~ '12345'
local_variables #=> ["a"]
instance_variables #=> []
global_variables.include?(:$a) #=> false
```

Prism's MatchWriteNode has wrong locals
```ruby
match_write_node = Prism.parse("/(?<a>.)(?<@a>.)(?<$a>.)(?<a b>.)/ =~ '12345'").value.statements.body[0]
match_write_node.locals
# => [:a, :@a, :$a, :"a b"]
```

Also, for `Prism.parse("/(?<a>)(?<a>)/ =~ s")`, locals are `[:a, :a]`. (I don't know if this is correct or wrong)

### PR DESCRIPTION
**Pull request by makenowjust**
Fix #1815

I think #1814 is partially fixed because this change makes the empty capture name `:""` not to be added to locals.

### CODE REVIEW

File: src/prism.c [hunk 1]
```diff
@@ -15383,6 +15402,10 @@ parse_regular_expression_named_captures(pm_parser_t *parser, const pm_string_t *
             const uint8_t *source = pm_string_source(name);
             size_t length = pm_string_length(name);
 
+            if (!name_is_identifier(parser, source, length)) {
```
Comment (kddnewton) [inline src/prism.c:15405]: I think this is good, but in this case it's possible to have a `MatchWriteNode` when there aren't actually any matches. In this case I think we shouldn't replace the call node with a match write. Instead, we could lazily create the `match` node once we are sure we have a named capture group that is valid, and then only set `result = match` if one was created.

**Review by kddnewton — CHANGES_REQUESTED** [review]

**Review by kddnewton — APPROVED** [review]
