### PR TITLE
 Fix `lex_state_beg_p`

### LINKED ISSUE #1572: Ruby accepts `def foo x:%(xx); end` but YARP rejects it
```
$ ./local/bin/irb -ryarp
irb(main):001> RubyVM::AbstractSyntaxTree.parse("def foo x:%(xx); end")
=>
(SCOPE@1:0-1:20
 tbl: []
 args: nil
 body:
   (DEFN@1:0-1:20
    mid: :foo
    body:
      (SCOPE@1:0-1:20
       tbl: [:x, nil]
       args: (ARGS@1:8-1:15 pre_num: 0 pre_init: nil opt: nil first_post: nil post_num: 0 post_init: nil rest: nil kw: (KW_ARG@1:8-1:15 (LASGN@1:8-1:15 :x (STR@1:10-1:15 "xx")) nil) kwrest: (DVAR@1:8-1:15 nil) block: nil)
       body: nil)))
irb(main):002> YARP.parse("def foo x:%(xx); end")
=>
#<YARP::ParseResult:0x00007f282d0a7a38
 @comments=[],
 @errors=
  [#<YARP::ParseError @message="Expected a delimiter to close the parameters" @location=#<YARP::Location @start_offset=10 @length=0 start_line=1>>,
   #<YARP::ParseError @message="Cannot parse the expression" @location=#<YARP::Location @start_offset=10 @length=0 start_line=1>>],
 @source=#<YARP::Source:0x00007f282cff27c8 @offsets=[0], @source="def foo x:%(xx); end">,
 @value=
  @ ProgramNode (location: (1,0)-(1,20))
  ├── locals: []
  └── statements:
      @ StatementsNode (location: (1,0)-(1,20))
      └── body: (length: 1)
          └── @ DefNode (location: (1,0)-(1,20))
              ├── name: :foo
              ├── name_loc: (1,4)-(1,7) = "foo"
              ├── receiver: ∅
              ├── parameters:
              │   @ ParametersNode (location: (1,8)-(1,10))
              │   ├── requireds: (length: 0)
              │   ├── optionals: (length: 0)
              │   ├── rest: ∅
              │   ├── posts: (length: 0)
              │   ├── keywords: (length: 1)
              │   │   └── @ KeywordParameterNode (location: (1,8)-(1,10))
              │   │       ├── name: :x
              │   │       ├── name_loc: (1,8)-(1,10) = "x:"
              │   │       └── value: ∅
              │   ├── keyword_rest: ∅
              │   └── block: ∅
              ├── body:
              │   @ StatementsNode (location: (1,10)-(1,15))
              │   └── body: (length: 2)
              │       ├── @ MissingNode (location: (1,10)-(1,10))
              │       └── @ ParenthesesNode (location: (1,11)-(1,15))
              │           ├── body:
              │           │   @ StatementsNode (location: (1,12)-(1,14))
              │           │   └── body: (length: 1)
              │           │       └── @ CallNode (location: (1,12)-(1,14))
              │           │           ├── receiver: ∅
              │           │           ├── call_operator_loc: ∅
              │           │           ├── message_loc: (1,12)-(1,14) = "xx"
              │           │           ├── opening_loc: ∅
              │           │           ├── arguments: ∅
              │           │           ├── closing_loc: ∅
              │           │           ├── block: ∅
              │           │           ├── flags: variable_call
              │           │           └── name: "xx"
              │           ├── opening_loc: (1,11)-(1,12) = "("
              │           └── closing_loc: (1,14)-(1,15) = ")"
              ├── locals: [:x]
              ├── def_keyword_loc: (1,0)-(1,3) = "def"
              ├── operator_loc: ∅
              ├── lparen_loc: ∅
              ├── rparen_loc: ∅
              ├── equal_loc: ∅
              └── end_keyword_loc: (1,17)-(1,20) = "end",
 @warnings=[]>
```

### LINKED ISSUE #1587: Ruby accepts `def f x:-a; end` but YARP rejects it
Same for `def f x:+a; end`
```ruby
irb(main):001> def f x:-a; end
=> :f
irb(main):002> YARP.parse 'def f x:-a; end'
=> 
#<YARP::ParseResult:0x00000001088e4708
 @comments=[],
 @errors=
  [#<YARP::ParseError @message="Expected a delimiter to close the parameters" @location=#<YARP::Location @start_offset=8 @length=0 start_line=1>>,
   #<YARP::ParseError @message="Cannot parse the expression" @location=#<YARP::Location @start_offset=8 @length=0 start_line=1>>],
 @source=#<YARP::Source:0x00000001085a2c98 @offsets=[0], @source="def f x:-a; end">,
 @value=
  @ ProgramNode (location: (1,0)-(1,15))
  ├── locals: []
  └── statements:
      @ StatementsNode (location: (1,0)-(1,15))
      └── body: (length: 1)
          └── @ DefNode (location: (1,0)-(1,15))
              ├── name: :f
              ├── name_loc: (1,4)-(1,5) = "f"
              ├── receiver: ∅
              ├── parameters:
              │   @ ParametersNode (location: (1,6)-(1,8))
              │   ├── requireds: (length: 0)
              │   ├── optionals: (length: 0)
              │   ├── rest: ∅
              │   ├── posts: (length: 0)
              │   ├── keywords: (length: 1)
              │   │   └── @ KeywordParameterNode (location: (1,6)-(1,8))
              │   │       ├── name: :x
              │   │       ├── name_loc: (1,6)-(1,8) = "x:"
              │   │       └── value: ∅
              │   ├── keyword_rest: ∅
              │   └── block: ∅
              ├── body:
              │   @ StatementsNode (location: (1,8)-(1,10))
              │   └── body: (length: 2)
              │       ├── @ MissingNode (location: (1,8)-(1,8))
              │       └── @ CallNode (location: (1,9)-(1,10))
              │           ├── receiver: ∅
              │           ├── call_operator_loc: ∅
              │           ├── message_loc: (1,9)-(1,10) = "a"
              │           ├── opening_loc: ∅
              │           ├── arguments: ∅
              │           ├── closing_loc: ∅
              │           ├── block: ∅
              │           ├── flags: variable_call
              │           └── name: "a"
              ├── locals: [:x]
              ├── def_keyword_loc: (1,0)-(1,3) = "def"
              ├── operator_loc: ∅
              ├── lparen_loc: ∅
              ├── rparen_loc: ∅
              ├── equal_loc: ∅
              └── end_keyword_loc: (1,12)-(1,15) = "end",
 @warnings=[]>

```

### PR DESCRIPTION
**Pull request by haldun**
Closes #1587
Closes #1572

### CODE REVIEW

**Comment by haldun** [comment]
@kddnewton wdyt about this one?

File: src/prism.c [hunk 1]
```diff
@@ -6912,7 +6912,7 @@ parser_lex(pm_parser_t *parser) {
                         );
                     }
 
-                    if (lex_state_beg_p(parser) || spcarg) {
+                    if (lex_state_beg_p(parser) || spcarg || parser->in_keyword_arg) {
```
Comment (kddnewton) [inline src/prism.c:6915]: I'm nervous about this change because it doesn't match up with `parse.y`, which makes me think we're missing some state change/detail. This line is equivalent to https://github.com/ruby/ruby/blob/486b674e2a8437bacb00c48038c04aec420c47a0/parse.y#L10801 which doesn't check if we're inside a keyword argument.

I did a little debugging and it looks like we're transitioning `BEG -> CMDARG` and they're transitioning `BEG -> ARG`. Maybe we're missing something here?

**Review by kddnewton — CHANGES_REQUESTED** [review]

File: src/prism.c (hunk 1 above)
Comment (haldun) [reply src/prism.c:6915]: We are transitioning to `CMDARG` here:

https://github.com/ruby/prism/blob/2dc5320289a01508e7fd59cc4ef8434d37706085/src/prism.c#L8840-L8848

because `previous_command_start` is `true`. An it is set to be `true` in https://github.com/ruby/prism/blob/2dc5320289a01508e7fd59cc4ef8434d37706085/src/prism.c#L14345-L14350

Comment (kddnewton) [reply src/prism.c:6915]: Yeah I wonder if that's not correct or if we're missing something here. Because we should definitely be transitioning to `ARG` and not `CMDARG`.

Comment (haldun) [reply src/prism.c]: It seemed quite unlikely but can `lex_state_beg_p` be just wrong? I attempted to fix it here and it seems like this bug gets resolved https://github.com/ruby/prism/pull/1591/commits/e854d479ad11bac055a3f80142b82fbf022771e4 Comparing with the Ruby implementation: https://github.com/ruby/ruby/blob/486b674e2a8437bacb00c48038c04aec420c47a0/parse.y#L347

Comment (haldun) [reply src/prism.c]: Also seems to fix https://github.com/ruby/prism/issues/1572

**Comment by haldun** [comment]
@kddnewton Can you take another look into this?

**Review by kddnewton — APPROVED** [review]
Great find!
