### PR TITLE
Prevent optional block parameter from accepting certain prefixed values

### LINKED ISSUE #1570: Ruby rejects `foo {|x=!1| }` but YARP accepts it
The same goes to other unary operators, such as `|x=+v|`.

```
$ ./local/bin/irb -ryarp
irb(main):001> RubyVM::AbstractSyntaxTree.parse("foo {|x=!1| }")
<internal:ast>:59:in `parse': syntax error, unexpected '!' (SyntaxError)
foo {|x=!1| }
        ^

        from (irb):1:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /home/mame/work/ruby/local/lib/ruby/gems/3.3.0+0/gems/irb-1.8.1/exe/irb:9:in `<top (required)>'
        from ./local/bin/irb:25:in `load'
        from ./local/bin/irb:25:in `<main>'
irb(main):002> YARP.parse("foo {|x=!1| }")
=>
#<YARP::ParseResult:0x00007f16946c8160
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007f16947586c0 @offsets=[0], @source="foo {|x=!1| }">,
 @value=
  @ ProgramNode (location: (1,0)-(1,13))
  ├── locals: []
  └── statements:
      @ StatementsNode (location: (1,0)-(1,13))
      └── body: (length: 1)
          └── @ CallNode (location: (1,0)-(1,13))
              ├── receiver: ∅
              ├── call_operator_loc: ∅
              ├── message_loc: (1,0)-(1,3) = "foo"
              ├── opening_loc: ∅
              ├── arguments: ∅
              ├── closing_loc: ∅
              ├── block:
              │   @ BlockNode (location: (1,4)-(1,13))
              │   ├── locals: [:x]
              │   ├── parameters:
              │   │   @ BlockParametersNode (location: (1,5)-(1,11))
              │   │   ├── parameters:
              │   │   │   @ ParametersNode (location: (1,6)-(1,10))
              │   │   │   ├── requireds: (length: 0)
              │   │   │   ├── optionals: (length: 1)
              │   │   │   │   └── @ OptionalParameterNode (location: (1,6)-(1,10))
              │   │   │   │       ├── name: :x
              │   │   │   │       ├── name_loc: (1,6)-(1,7) = "x"
              │   │   │   │       ├── operator_loc: (1,7)-(1,8) = "="
              │   │   │   │       └── value:
              │   │   │   │           @ CallNode (location: (1,8)-(1,10))
              │   │   │   │           ├── receiver:
              │   │   │   │           │   @ IntegerNode (location: (1,9)-(1,10))
              │   │   │   │           │   └── flags: decimal
              │   │   │   │           ├── call_operator_loc: ∅
              │   │   │   │           ├── message_loc: (1,8)-(1,9) = "!"
              │   │   │   │           ├── opening_loc: ∅
              │   │   │   │           ├── arguments: ∅
              │   │   │   │           ├── closing_loc: ∅
              │   │   │   │           ├── block: ∅
              │   │   │   │           ├── flags: ∅
              │   │   │   │           └── name: "!"
              │   │   │   ├── rest: ∅
              │   │   │   ├── posts: (length: 0)
              │   │   │   ├── keywords: (length: 0)
              │   │   │   ├── keyword_rest: ∅
              │   │   │   └── block: ∅
              │   │   ├── locals: (length: 0)
              │   │   ├── opening_loc: (1,5)-(1,6) = "|"
              │   │   └── closing_loc: (1,10)-(1,11) = "|"
              │   ├── body: ∅
              │   ├── opening_loc: (1,4)-(1,5) = "{"
              │   └── closing_loc: (1,12)-(1,13) = "}"
              ├── flags: ∅
              └── name: "foo",
 @warnings=[]>
```

### PR DESCRIPTION
**Pull request by st0012**
This commit prevents the following unary operators from being accepted as the value prefix of a block's optional parameter:

- `+`
- `-`
- `~`
- `!`

For example, `f { |a = +b| }` will now raise a syntax error.

Closes #1570

### CODE REVIEW

File: templates/src/diagnostic.c.erb [hunk 1]
```diff
@@ -344,6 +344,7 @@ static const pm_diagnostic_data_t diagnostic_messages[PM_DIAGNOSTIC_ID_MAX] = {
     [PM_ERR_TERNARY_EXPRESSION_TRUE]            = { "expected an expression after `?` in the ternary operator", PM_ERROR_LEVEL_SYNTAX },
     [PM_ERR_UNDEF_ARGUMENT]                     = { "invalid argument being passed to `undef`; expected a bare word, constant, or symbol argument", PM_ERROR_LEVEL_SYNTAX },
     [PM_ERR_UNARY_RECEIVER]                     = { "unexpected %s, expected a receiver for unary `%c`", PM_ERROR_LEVEL_SYNTAX },
+    [PM_ERR_UNARY_DISALLOWED]                   = { "unexpected %s", PM_ERROR_LEVEL_SYNTAX },
```
Comment (kddnewton) [inline templates/src/diagnostic.c.erb:347]:
```suggestion
    [PM_ERR_UNARY_DISALLOWED]                   = { "unexpected %s; unary calls are not allowed in this context", PM_ERROR_LEVEL_SYNTAX },
```

can we make this a little more explicit?

**Review by kddnewton — CHANGES_REQUESTED** [review]

**Review by kddnewton — APPROVED** [review]
