### PR TITLE
Fix LocalVariableTargetNode depth in patterns

### LINKED ISSUE #1821: MatchRequiredNide is not scoping variables correctly
In this snippet `a` should have a depth of 1.  It is 0 like `b`:

```ruby
a = nil
proc {
  [0, 1] => [a, b]
}.call
p [a, defined?(b)]
```

AST:

```text
@ ProgramNode (location: (1,0)-(5,18))
├── locals: [:a]
└── statements:
    @ StatementsNode (location: (1,0)-(5,18))
    └── body: (length: 3)
        ├── @ LocalVariableWriteNode (location: (1,0)-(1,7))
        │   ├── name: :a
        │   ├── depth: 0
        │   ├── name_loc: (1,0)-(1,1) = "a"
        │   ├── value:
        │   │   @ NilNode (location: (1,4)-(1,7))
        │   └── operator_loc: (1,2)-(1,3) = "="
        ├── @ CallNode (location: (2,0)-(4,6))
        │   ├── receiver:
        │   │   @ CallNode (location: (2,0)-(4,1))
        │   │   ├── receiver: ∅
        │   │   ├── call_operator_loc: ∅
        │   │   ├── message_loc: (2,0)-(2,4) = "proc"
        │   │   ├── opening_loc: ∅
        │   │   ├── arguments: ∅
        │   │   ├── closing_loc: ∅
        │   │   ├── block:
        │   │   │   @ BlockNode (location: (2,5)-(4,1))
        │   │   │   ├── locals: [:a, :b]
        │   │   │   ├── parameters: ∅
        │   │   │   ├── body:
        │   │   │   │   @ StatementsNode (location: (3,2)-(3,18))
        │   │   │   │   └── body: (length: 1)
        │   │   │   │       └── @ MatchRequiredNode (location: (3,2)-(3,18))
        │   │   │   │           ├── value:
        │   │   │   │           │   @ ArrayNode (location: (3,2)-(3,8))
        │   │   │   │           │   ├── elements: (length: 2)
        │   │   │   │           │   │   ├── @ IntegerNode (location: (3,3)-(3,4))
        │   │   │   │           │   │   │   └── flags: decimal
        │   │   │   │           │   │   └── @ IntegerNode (location: (3,6)-(3,7))
        │   │   │   │           │   │       └── flags: decimal
        │   │   │   │           │   ├── opening_loc: (3,2)-(3,3) = "["
        │   │   │   │           │   └── closing_loc: (3,7)-(3,8) = "]"
        │   │   │   │           ├── pattern:
        │   │   │   │           │   @ ArrayPatternNode (location: (3,12)-(3,18))
        │   │   │   │           │   ├── constant: ∅
        │   │   │   │           │   ├── requireds: (length: 2)
        │   │   │   │           │   │   ├── @ LocalVariableTargetNode (location: (3,13)-(3,14))
        │   │   │   │           │   │   │   ├── name: :a
        │   │   │   │           │   │   │   └── depth: 0
        │   │   │   │           │   │   └── @ LocalVariableTargetNode (location: (3,16)-(3,17))
        │   │   │   │           │   │       ├── name: :b
        │   │   │   │           │   │       └── depth: 0
        │   │   │   │           │   ├── rest: ∅
        │   │   │   │           │   ├── posts: (length: 0)
        │   │   │   │           │   ├── opening_loc: (3,12)-(3,13) = "["
        │   │   │   │           │   └── closing_loc: (3,17)-(3,18) = "]"
        │   │   │   │           └── operator_loc: (3,9)-(3,11) = "=>"
        │   │   │   ├── opening_loc: (2,5)-(2,6) = "{"
        │   │   │   └── closing_loc: (4,0)-(4,1) = "}"
        │   │   ├── flags: ∅
        │   │   └── name: :proc
        │   ├── call_operator_loc: (4,1)-(4,2) = "."
        │   ├── message_loc: (4,2)-(4,6) = "call"
        │   ├── opening_loc: ∅
        │   ├── arguments: ∅
        │   ├── closing_loc: ∅
        │   ├── block: ∅
        │   ├── flags: ∅
        │   └── name: :call
        └── @ CallNode (location: (5,0)-(5,18))
            ├── receiver: ∅
            ├── call_operator_loc: ∅
            ├── message_loc: (5,0)-(5,1) = "p"
            ├── opening_loc: ∅
            ├── arguments:
            │   @ ArgumentsNode (location: (5,2)-(5,18))
            │   ├── arguments: (length: 1)
            │   │   └── @ ArrayNode (location: (5,2)-(5,18))
            │   │       ├── elements: (length: 2)
            │   │       │   ├── @ LocalVariableReadNode (location: (5,3)-(5,4))
            │   │       │   │   ├── name: :a
            │   │       │   │   └── depth: 0
            │   │       │   └── @ DefinedNode (location: (5,6)-(5,17))
            │   │       │       ├── lparen_loc: (5,14)-(5,15) = "("
            │   │       │       ├── value:
            │   │       │       │   @ CallNode (location: (5,15)-(5,16))
            │   │       │       │   ├── receiver: ∅
            │   │       │       │   ├── call_operator_loc: ∅
            │   │       │       │   ├── message_loc: (5,15)-(5,16) = "b"
            │   │       │       │   ├── opening_loc: ∅
            │   │       │       │   ├── arguments: ∅
            │   │       │       │   ├── closing_loc: ∅
            │   │       │       │   ├── block: ∅
            │   │       │       │   ├── flags: variable_call
            │   │       │       │   └── name: :b
            │   │       │       ├── rparen_loc: (5,16)-(5,17) = ")"
            │   │       │       └── keyword_loc: (5,6)-(5,14) = "defined?"
            │   │       ├── opening_loc: (5,2)-(5,3) = "["
            │   │       └── closing_loc: (5,17)-(5,18) = "]"
            │   └── flags: ∅
            ├── closing_loc: ∅
            ├── block: ∅
            ├── flags: ∅
            └── name: :p
```

### PR DESCRIPTION
**Pull request by makenowjust**
Fix #1821

### CODE REVIEW

File: src/prism.c [hunk 1]
```diff
@@ -4136,6 +4136,22 @@ pm_local_variable_target_node_create(pm_parser_t *parser, const pm_token_t *name
...
+    pm_refute_numbered_parameter(parser, name->start, name->end);
+
+    return pm_local_variable_target_node_create_values(
+        parser,
+        &(pm_location_t) { .start = name->start, .end = name->end },
+        pm_parser_constant_id_token(parser, name),
+        depth
+    );
+}
+
```
Comment (kddnewton) [inline src/prism.c:4153]:
```suggestion
```

**Review by kddnewton — APPROVED** [review]

File: src/prism.c (hunk 1 above)
Comment (makenowjust) [reply src/prism.c:4153]: Good catch👍 Thank you.

**Comment by kddnewton** [comment]
@makenowjust just needs a rebase
