### PR TITLE
Fix lex state for undef, and multi-arg undef

### LINKED ISSUE #381: Fix state on undef
Examples in test suite that are currently incorrect:

```
undef a
```

```
undef a, b
```

### PR DESCRIPTION
**Pull request by jemmaissroff**
`rake lex` goes from 94.37% -> 94.5%

Closes #381

### CODE REVIEW

File: src/yarp.c [hunk 1]
```diff
@@ -6129,7 +6129,9 @@ parse_expression_prefix(yp_parser_t *parser, binding_power_t binding_power) {
 
       yp_undef_node_append(undef, name);
 
-      while (accept(parser, YP_TOKEN_COMMA)) {
+      while (match_type_p(parser, YP_TOKEN_COMMA)) {
+        lex_state_set(parser, YP_LEX_STATE_FNAME | YP_LEX_STATE_FITEM);
```
Comment (jemmaissroff) [inline src/yarp.c:6133]: This matches [this line](https://github.com/ruby/ruby/blob/f313514563853f1ee623135c2959df2b518ee755/parse.y#L2567) in Ripper's `parse.y`
