### PR TITLE
Fix locations derived from arguments

### LINKED ISSUE #1895: SuperNode location does not include closing parenthesis
```
bin/parse -e 'def m; super(*args, &block); end'
...
            │       └── @ SuperNode (location: (1,7)-(1,26))
            │           ├── keyword_loc: (1,7)-(1,12) = "super"
            │           ├── lparen_loc: (1,12)-(1,13) = "("
            │           ├── arguments:
            │           │   @ ArgumentsNode (location: (1,13)-(1,18))
            │           │   ├── arguments: (length: 1)
            │           │   │   └── @ SplatNode (location: (1,13)-(1,18))
            │           │   │       ├── operator_loc: (1,13)-(1,14) = "*"
            │           │   │       └── expression:
            │           │   │           @ CallNode (location: (1,14)-(1,18))
            │           │   │           ├── receiver: ∅
            │           │   │           ├── call_operator_loc: ∅
            │           │   │           ├── name: :args
            │           │   │           ├── message_loc: (1,14)-(1,18) = "args"
            │           │   │           ├── opening_loc: ∅
            │           │   │           ├── arguments: ∅
            │           │   │           ├── closing_loc: ∅
            │           │   │           ├── block: ∅
            │           │   │           └── flags: variable_call
            │           │   └── flags: ∅
            │           ├── rparen_loc: (1,26)-(1,27) = ")"
            │           └── block:
            │               @ BlockArgumentNode (location: (1,20)-(1,26))
            │               ├── expression:
            │               │   @ CallNode (location: (1,21)-(1,26))
            │               │   ├── receiver: ∅
            │               │   ├── call_operator_loc: ∅
            │               │   ├── name: :block
            │               │   ├── message_loc: (1,21)-(1,26) = "block"
            │               │   ├── opening_loc: ∅
            │               │   ├── arguments: ∅
            │               │   ├── closing_loc: ∅
            │               │   ├── block: ∅
            │               │   └── flags: variable_call
            │               └── operator_loc: (1,20)-(1,21) = "&"
```
See `SuperNode (location: (1,7)-(1,26))`, `keyword_loc: (1,7)-(1,12) = "super"`, `rparen_loc: (1,26)-(1,27) = ")"`.

### PR DESCRIPTION
**Pull request by haldun**
Fixes the locations of a few nodes where the location is derived from `pm_arguments_t`.

Closes #1895

### CODE REVIEW

File: src/prism.c [hunk 1]
```diff
@@ -796,6 +796,27 @@ typedef struct {
     pm_node_t *block;
 } pm_arguments_t;
 
+/**
+ * Retrieve the end location of a `pm_arguments_t` object.
+ */
+static inline const uint8_t *
+arguments_end_location(pm_arguments_t *arguments) {
```
Comment (kddnewton) [inline src/prism.c:803]: I know this is static, but can you call it `pm_arguments_end` anyway?

**Review by kddnewton — CHANGES_REQUESTED** [review]

File: src/prism.c (hunk 1 above)
Comment (haldun) [reply src/prism.c:803]: Sure. I was not happy with that name too but couldn't figure out a good one.

**Review by kddnewton — APPROVED** [review]
